### ISSUE TITLE
Review variables

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#120]
Check all the variables to reduce their size as much as possible. Change floats to in etc..

(Just moving some notes from t400.ino into issues)

**Comment by charlespax** [comment]
Memory issue.

**Comment by cibomahto** [comment]
Did a pass at this and there aren't any obvious mis-uses of memory in the main program. Arduino 1.6 compilation estimates 72% memory used by static variables. 

Note that floats are the same size as ints: https://gcc.gnu.org/wiki/avr-gcc
The main advantage for ints is that the code to processes them is much shorter, since the processor can only handle 8 (and limited 16) bit integer math directly.
