### ISSUE TITLE
Measure battery voltage

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#18]
The circuit allows for measuring the LiPo battery voltage. This is not very accurate, but it can give a sense of how must battery power remains.

**Comment by cibomahto** [comment]
Note that either the 3.3V regulator or internal voltage reference could be used to make this masurement.

**Comment by charlespax** [comment]
We are using the ATmega32U4 internal voltage reference (https://github.com/PaxInstruments/t400-firmware/issues/21) as of Electronics version 0.10. AREF is no longer connected to 3.3V.

**Comment by charlespax** [comment]
We have decoupled AREF to improve noise immunity. I believe using 3.3V to measure battery is not an option.

![image](https://cloud.githubusercontent.com/assets/1327611/5643432/7c9d0b98-9693-11e4-8417-7d277e2edd3b.png)

**Comment by cibomahto** [comment]
It's available as AVcc, but the internal reference is probably more stable. I don't have high expectations for this measurement anyway, since it's not doing charge counting.

![screen shot 2015-02-22 at 10 14 24 am](https://cloud.githubusercontent.com/assets/44493/6317563/844fbba8-ba95-11e4-9732-5b79d3fa032d.png)

**Comment by cibomahto** [comment]
Logic for this implemented in 4036215. Note that the calibration values will need to be updated depending on the battery; I'm making a new issue for that, to revisit after you've chosen the final battery. Also note that this is likely to be very inaccurate just because measuring the battery voltage is a poor way of determining it's charge state.
